source 'http://rubygems.org'

gem 'rails', '=3.0.1'
gem 'sqlite3-ruby', '=1.3.2', :require => 'sqlite3'
gem "makandra_resource_controller", :path => "../"

gem 'redgreen', '=1.2.2'

group :test do
  gem "shoulda", '=2.11.3'
  gem "mocha", '=0.9.9'
  gem "ruby-debug", '=0.10.4'
end
