source 'http://rubygems.org'

gem 'rails', '3.0.0.beta3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem "resource_controller", :require => "resource_controller", :path => "../"

group :test do
    gem "shoulda", :git => "git://github.com/thoughtbot/shoulda.git", :branch => "rails3"
    gem "mocha"
end
